name: Chris Mair
favicon: null
layout_spectrum: 0.99455
typography_spectrum: 0.5397875625640154
title: Chris
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#540d03'
    - '#d26c12'
    - '#e8a219'
    - '#fadb33'
  brandStrength: 0.75
  lightness: 0.3059925213456154
  saturation: 0.08103241957724094
  rhythmicContrast: 0.87325170612894
purpose: []
